### ISSUE TITLE
Installation for other coin

### ISSUE THREAD

**Issue by Royaltropico** [Karbovanets/Karbowanec-Blockchain-Explorer#1]
Hello,
How can I install it with forknote? I added the following code to the coin's config file (with no success):
rpc-bind-ip=0.0.0.0
enable-blockchain-indexes=1
enable-cors=*

My coin: http:/tropicohedge.org
Block Explorer: http:/blockexplorer.tropicohedge.org
Thanks.

**Comment by aivve** [comment]
It should work, although not all features maybe. If your forknoted started with these parameters then it will work. Edit config.js and point explorer to the daemon's external IP or domain and port.

**Comment by leisegang** [comment]
i use these settings, but i cannot get the difficulty listed.
https://www.leisegang.no/src/WXYZjKMP.png
