### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by servc4** [Karbovanets/Karbowanec-Blockchain-Explorer#8]
Hi
I try to use Yours Block explorer to Bytecoin, but I can't run daemon with this command
./bytecoind --restricted-rpc --enable-cors=* --enable-blockchain-indexes --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18081

I lunch it with command 

./bytecoind --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18081

and I am able to check data from the daemon on different host:
When I run command:

curl Myhost.com:18081/json_rpc -d '{"method":"getblockheaderby height","params":{"height":100}}'

I get answer
{"jsonrpc":"2.0","result":{"block_header":{"depth":1640,"difficulty":3948,"hash":"67cde8b9a3995b83ec2deecd97f567890ea1a56d964af7f0bdd5e2b77844a605","height":99,"major_version":3,"minor_version":0,"nonce":2149190104,"orphan_status":false,"prev_hash":"e95a546eebeb47916e310e763be0fa723079bdb865dda3a6b938054e21788d33","reward":70342174034331,"timestamp":1512523086},"status":"OK"}}

then in config I set
var api = "Myhost:18081";
 and there is no results..
 Any idea why ??

**Comment by Royaltropico** [comment]
Same result

**Comment by servc4** [comment]
Hi
I made some changes in my source...
and now answer on command
`curl -s -X POST 127.0.0.1:18081/json_rpc -d '{"params": {"hash" : "abb030db953218630ff656a6487e79098acc9b62b316e23c186b88ad1a9bad9a"} ,"jsonrpc":"2.0","id":"test","method":"f_block_json"}' -H 'Content-Type: application/json'`

Is:

`{"id":"test","jsonrpc":"2.0","result":{"block":{"alreadyGeneratedCoins":"1749749696798552973","alreadyGeneratedTransactions":29747,"baseReward":63694221767932,"blockSize":550,"depth":0,"difficulty":9609537,"effectiveSizeMedian":100000,"hash":"abb030db953218630ff656a6487e79098acc9b62b316e23c186b88ad1a9bad9a","height":26124,"major_version":3,"minor_version":0,"nonce":581693486,"orphan_status":false,"penalty":0.0,"prev_hash":"a39cc082b709231d5209ab7fd4ef51b29ed6c86ca2030a83afbc3ea9ee196971","reward":63694221767932,"sizeMedian":395,"timestamp":1517180998,"totalFeeAmount":0,"transactions":[{"amount_out":63694221767932,"fee":0,"hash":"95443f8a7fce21c57da6b1b2370f56cea0d48c2b096065908f05ddf685e93a4a","size":431}],"transactionsCumulativeSize":431},"status":"OK"}}`

looks ok but explorer still not work
any suggestion ??

**Comment by servc4** [comment]
Hi
I almost lunch properly working explorer but I have issue with CROS header
` Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:18081/getinfo. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

How I can resolve that problem
.htaccess
```
Header set Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```
Is not working
I need to have ad-don in my browser to view page properly.

Regards

**Comment by servc4** [comment]
Hi 
Can someone help me with transaction pool, becouse I don't have any data...
the code is:

```
function getPoolTransactions(){

var xhrGetPool = $.ajax({

            url: api + '/json_rpc',
            method: "POST",
            data: JSON.stringify({
                jsonrpc:"2.0",
                id: "test",
                method:"f_on_transactions_pool_json",
                params: {

                }
            }),
            dataType: 'text',
            cache: 'false',
            success: function(data){

                                var txsRows = document.getElementById('mem_pool_rows');
                                while (txsRows.firstChild) {
                                        txsRows.removeChild(txsRows.firstChild);
                                }

                                var rawTxs = data.split('"transactions":"').pop();
                                rawTxs = rawTxs.split('"}}')[0];
                                var txsArray = [];
                                txsArray = rawTxs.split('\n\n');
                                txsArray.forEach(function(tx, i) {
                                        var arrayOfLines = tx.split('\n');
                                        var hash = arrayOfLines[0].split(': ').pop();
                                        if(hash != "") {
                                                var timestamp = arrayOfLines[10].split(':').pop();
                                                var amount = arrayOfLines[8].split(':').pop();
                                                var fee = arrayOfLines[9].split(':').pop();
                                                var size = arrayOfLines[1].split(':').pop();
                                                var row = document.createElement('tr');
                                                var columns =
                                                                '<td>' + formatDate(timestamp) + ' (<span class="mtx-ago"></span>)' + '</td>' +
                                                                '<td>' + getReadableCoins(amount, 4, true) + '</td>' +
                                                                '<td>' + getReadableCoins(fee, 4, true) + '</td>' +
                                                                '<td>' + size + '</td>' +
                                                                '<td>' + formatPaymentLink(hash) + '</td>';
                                                row.innerHTML = columns;
                                                $(txsRows).append(row);
                                                $(row).find('.mtx-ago').timeago('update', new Date(timestamp * 1000).toISOString());
                                        }
                                });
                                updateText('mempool_count', document.querySelectorAll('#mem_pool_rows tr').length);
                        }
    });
};
```

Answer from server is:
`{"id":"test","jsonrpc":"2.0","result":{"status":"OK","transactions":[{"amount_out":441285055013830,"fee":10000000000,"hash":"8be64340c5d21c0ae7e8202dd1274020c7d30cf61d9578714fa1b04e50444106","size":14462}]}}`

but no data on website at all...

Regards

**Comment by Royaltropico** [comment]
I lunch it with:
./forknoted --config-file configs / mymoney.conf --rpc-bind-ip = 0.0.0.0 --rpc-bind-port = 41018
I tested with the Karbowanec block-explorer (IP) and everything works fine but with my daemon I have no info except by doing this: Click on "Blockchain Explorer", enter the desired height, click on "GO" and then click on "Blockchain Explorer" at the top of the menu.
To develop the Block Hash, click on the desired Block Hash, then click on "Block Explorer" and finally click on the previous page in your browser and the information will be displayed

**Comment by MichaelHarrel1993** [comment]
Hi serv4 , how did you resolve Access-Control-Allow-Origin error ?

**Comment by servc4** [comment]
Hi
I'm working on it, give me half hour to confirm if is working or not.
For now I used addons to browser 
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/
